### PR TITLE
Use 10 PEXECS by default.

### PR DESCRIPTION
**Pull request by snim2**

### CODE REVIEW

**Comment by ltratt** [comment]
The comment about "30 in the paper" is accurate, but maybe a bit confusing now? Should we update / remove it?

**Comment by snim2** [comment]
Is that an improvement?

**Comment by ltratt** [comment]
It's still a bit confusing; but I've tried rephrasing it, and not done any better. So, on reflection, I actually think we should just remove the comment. Thoughts?

**Comment by snim2** [comment]
Hmm. The iterations counter is in a JSON file, so we can't have a comment there anyhow. The Makefile currently says:

```
	@echo "To run the example benchmark, cd to the v8 dir and run ../scripts/${RUN_SCRIPT}"
	@echo "To use fewer process executions, edit the PEXECS variable in scripts/${RUN_SCRIPT}."
	@echo "To use fewer iterations, edit 'run_count' in v8/benchmarks/sd-v8.json."
```

Perhaps we should put a note about defaults in the paper there?

**Comment by ltratt** [comment]
I think we should just divorce the paper from this a little bit: in a sense, it doesn't matter what the paper said, because we're going to use different values here.

**Comment by snim2** [comment]
OK, but I wonder if people will think "why those defaults?"

**Comment by ltratt** [comment]
Agreed, that is a risk. But since 10 isn't the value we used in the paper, does pointing them at the paper help?

**Comment by snim2** [comment]
Well, 10 is derived from Figure 9/10 in the paper, right?

**Comment by ltratt** [comment]
Yes, but in a slightly bogus way -- there's no reason to assume that 10 pexecs is a good value for any benchmark suite other than that in the paper. Put another way, we've just guessed that 10 is an OK value for this benchmark suite ;)

**Comment by snim2** [comment]
OK, in that case I think we are ready to squash?

**Comment by ltratt** [comment]
Agreed -- let's squash.

**Comment by snim2** [comment]
Squashed

**Pull request merged**
